s = set()
num = input("Enter the number 1: ")
s.add(int(num))
num = input("Enter the number 2: ")
s.add(int(num))
num = input("Enter the number 3: ")
s.add(int(num))
num = input("Enter the number 4: ")
s.add(int(num))
num = input("Enter the number 5: ")
s.add(int(num))
num = input("Enter the number 6: ")
s.add(int(num))
num = input("Enter the number 7: ")
s.add(int(num))
num = input("Enter the number 8: ")
s.add(int(num))

print(s)

